FROM ubuntu:16.04

RUN apt-get update && apt-get install -y doxygen graphviz

COPY doc /novo/doc
COPY src /novo/src

WORKDIR /novo

RUN doxygen doc/Doxyfile

FROM nginx:alpine

COPY --from=0 /novo/doc/doxygen/html /usr/share/nginx/html
